"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class WriteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TIMESERIES_FIELD_NUMBER: builtins.int
    @property
    def timeseries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TimeSeries]: ...
    def __init__(self,
        *,
        timeseries: typing.Optional[typing.Iterable[global___TimeSeries]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["timeseries",b"timeseries"]) -> None: ...
global___WriteRequest = WriteRequest

class ReadRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    QUERIES_FIELD_NUMBER: builtins.int
    @property
    def queries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Query]: ...
    def __init__(self,
        *,
        queries: typing.Optional[typing.Iterable[global___Query]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["queries",b"queries"]) -> None: ...
global___ReadRequest = ReadRequest

class ReadResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESULTS_FIELD_NUMBER: builtins.int
    @property
    def results(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___QueryResult]:
        """In same order as the request's queries."""
        pass
    def __init__(self,
        *,
        results: typing.Optional[typing.Iterable[global___QueryResult]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["results",b"results"]) -> None: ...
global___ReadResponse = ReadResponse

class Query(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    START_TIMESTAMP_MS_FIELD_NUMBER: builtins.int
    END_TIMESTAMP_MS_FIELD_NUMBER: builtins.int
    MATCHERS_FIELD_NUMBER: builtins.int
    HINTS_FIELD_NUMBER: builtins.int
    start_timestamp_ms: builtins.int
    end_timestamp_ms: builtins.int
    @property
    def matchers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LabelMatcher]: ...
    @property
    def hints(self) -> global___ReadHints: ...
    def __init__(self,
        *,
        start_timestamp_ms: builtins.int = ...,
        end_timestamp_ms: builtins.int = ...,
        matchers: typing.Optional[typing.Iterable[global___LabelMatcher]] = ...,
        hints: typing.Optional[global___ReadHints] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["hints",b"hints"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["end_timestamp_ms",b"end_timestamp_ms","hints",b"hints","matchers",b"matchers","start_timestamp_ms",b"start_timestamp_ms"]) -> None: ...
global___Query = Query

class QueryResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TIMESERIES_FIELD_NUMBER: builtins.int
    @property
    def timeseries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TimeSeries]:
        """Samples within a time series must be ordered by time."""
        pass
    def __init__(self,
        *,
        timeseries: typing.Optional[typing.Iterable[global___TimeSeries]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["timeseries",b"timeseries"]) -> None: ...
global___QueryResult = QueryResult

class Sample(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VALUE_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    value: builtins.float
    timestamp: builtins.int
    def __init__(self,
        *,
        value: builtins.float = ...,
        timestamp: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["timestamp",b"timestamp","value",b"value"]) -> None: ...
global___Sample = Sample

class TimeSeries(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LABELS_FIELD_NUMBER: builtins.int
    SAMPLES_FIELD_NUMBER: builtins.int
    @property
    def labels(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Label]: ...
    @property
    def samples(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Sample]: ...
    def __init__(self,
        *,
        labels: typing.Optional[typing.Iterable[global___Label]] = ...,
        samples: typing.Optional[typing.Iterable[global___Sample]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["labels",b"labels","samples",b"samples"]) -> None: ...
global___TimeSeries = TimeSeries

class Label(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    name: typing.Text
    value: typing.Text
    def __init__(self,
        *,
        name: typing.Text = ...,
        value: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name","value",b"value"]) -> None: ...
global___Label = Label

class Labels(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LABELS_FIELD_NUMBER: builtins.int
    @property
    def labels(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Label]: ...
    def __init__(self,
        *,
        labels: typing.Optional[typing.Iterable[global___Label]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["labels",b"labels"]) -> None: ...
global___Labels = Labels

class LabelMatcher(google.protobuf.message.Message):
    """Matcher specifies a rule, which can match or set of labels or not."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _Type:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[LabelMatcher._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        EQ: LabelMatcher._Type.ValueType  # 0
        NEQ: LabelMatcher._Type.ValueType  # 1
        RE: LabelMatcher._Type.ValueType  # 2
        NRE: LabelMatcher._Type.ValueType  # 3
    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        pass

    EQ: LabelMatcher.Type.ValueType  # 0
    NEQ: LabelMatcher.Type.ValueType  # 1
    RE: LabelMatcher.Type.ValueType  # 2
    NRE: LabelMatcher.Type.ValueType  # 3

    TYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    type: global___LabelMatcher.Type.ValueType
    name: typing.Text
    value: typing.Text
    def __init__(self,
        *,
        type: global___LabelMatcher.Type.ValueType = ...,
        name: typing.Text = ...,
        value: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name","type",b"type","value",b"value"]) -> None: ...
global___LabelMatcher = LabelMatcher

class ReadHints(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STEP_MS_FIELD_NUMBER: builtins.int
    FUNC_FIELD_NUMBER: builtins.int
    START_MS_FIELD_NUMBER: builtins.int
    END_MS_FIELD_NUMBER: builtins.int
    step_ms: builtins.int
    """Query step size in milliseconds."""

    func: typing.Text
    """String representation of surrounding function or aggregation."""

    start_ms: builtins.int
    """Start time in milliseconds."""

    end_ms: builtins.int
    """End time in milliseconds."""

    def __init__(self,
        *,
        step_ms: builtins.int = ...,
        func: typing.Text = ...,
        start_ms: builtins.int = ...,
        end_ms: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["end_ms",b"end_ms","func",b"func","start_ms",b"start_ms","step_ms",b"step_ms"]) -> None: ...
global___ReadHints = ReadHints
